### ISSUE TITLE
Des nouvelles commandes

### ISSUE THREAD

**Issue by Gynidark** [Grafikart/GrafikartBot-Elixir#1]
**Doc**

> L'idée est de renvoyer un utilisateur sur la documentation en question avec un message doux.

- !doc @Grafikart {php, js, html, nodejs, ...}

### Beginner

> Cette commande serait vraiment sympa pour les débutants, il est très difficile de faire les bons choix quand nous commençons. L'idée de la commande ça serait de lui renvoyer un liens d'une formation complète. Par exemple : !beginner @Gynidark php et là il me renvoie l'url [Apprendre le PHP en étant débutant](https://www.grafikart.fr/formations/php-debutant) avec un message cool.

- !beginner @Grafikart {php, js, html, nodejs, python,, ...etc}

### Networks

>Permet d'avoir tout t'es réseaux sociaux

- !networks 
- !networks {github, twitter, ...}

### Quota

> Permettrai d'éviter les personnes qui pose beaucoup trop de question.
*accessible que par les administrateurs.*

- !quota @Grafikart {number}

### Grafikart(à revoir)

> L'idée serait de revoir cette commande afin déjà d'éviter les recherches vide et d'ajouter les tutoriels approprié à la recherche directement.

- !grafikart maildev

et là tu l'amène directement à ce [lien](https://www.grafikart.fr/tutoriels/divers/maildev-tester-emails-595) bon après c'est un petit ajout.

### Eve

> Beaucoup sont dans le développement, mais ne font pas de veille. Ça serait cool d'avoir cette commande.

- !eve 

et elle renverrez vers un lien hastebin avec tout les sites,twitters utiles. 💯 

### "J'ai un problème"

> Éviter les "J'ai un problème ...." à tout bout de champ. L'idée serait de donner un acheminement pour qu'il puissent expliquer sont problème correctement.

___________
Voilà 😃

**Comment by Grafikart** [comment]
## Doc

La commande doc je préfère la faire comme pour php
!php .... 
Après il faut voir quelles docs sont pertinentes.

## Networks

Je ne pense pas qu'elle soit utile

## Quota

Je pense l'implémenté mais plutôt l'appelle limit, il faut voir comment on applique la limite (les valeurs à mettre). Donc il faut voir sur le tchat la fréquence de post des personnes qui "spams" les questions

## Eve

Ne sert à rien, peut être remplacé par un chan avec des liens

## "J'ai un problème"

Le risque est de chopper trop de message, comme pour la commande quota il faudrait lister les "phrases" inutiles pour en extraire un pattern

**Comment by lhuteau-metacraft** [comment]
Eve

Super utile, beaucoup ne savent pas par ou commencer dans une veille technologique

Network : 

Peut être améliorer en pouvant rajouter chacun ces reseaus sociaux dans une bdd et pouvoir faire !network @Grafikart par exemple

**Comment by romainromss** [comment]
!eve   

 Je suis pour aussi a condition de vérifier les sites avant d'ajouter.  
Ajouter des liens dans un chan pourquoi pas ? mais peut être les épingler alors  et ajouter les liens valides ?

**Comment by EG-Julien** [comment]
Tu voulais des sample : Bonjour qui s'y connaît bien en Rails please ? n'est pas détecter par le bot :dagger:
